[project]
name = "strixpipeline"
version = "2.0.0-dev"
description = ""
readme = "README.md"
requires-python = ">=3.14"
license = "MIT"
authors = [
  { name = "Språkbanken", email = "sb-info@svenska.gu.se" }
]

dependencies = [
  "elasticsearch==8.15.1",
  "elasticsearch-dsl==8.12.0",
  "PyYAML==6.0.1",
  "orjson==3.11.3",
  "snakemake==9.13.4",
]

[project.optional-dependencies]
dev = [
  "ruff==0.5.7",
  "basedpyright"
]


[project.scripts]
strix-pipeline = "strixpipeline.cli:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["strixpipeline"]

[tool.ruff]
target-version = "py314"

[tool.basedpyright]
pythonVersion = "3.14"
